POST http://localhost:7008/api/auth/register

{
"email":"patrick_the_awesome2_12345678910@12345678910.dk",
"password":"123456789",
"phone":"88888888",
"name":"patrick_the_awesome"
}

###

POST http://localhost:7008/api/auth/login

{
"email":"patrick_the_awesome2_12345678910@12345678910.dk",
"password":"123456789"
}

###

GET http://localhost:7008/api/auth/request/password/reset?email=12345678910@12345678910.dk

###

GET http://localhost:7008/api/auth/reset/password?email=12345678910@12345678910.dk&guid=

###

GET http://localhost:7008/api/events/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcm91cCBvbmUiLCJzdWIiOiIxMjM0NTY3ODkxMEAxMjM0NTY3ODkxMC5kayIsImV4cCI6MTcxMjI1NjU3NCwicm9sZXMiOiJJTlNUUlVDVE9SIiwidXNlcm5hbWUiOiIxMjM0NTY3ODkxMEAxMjM0NTY3ODkxMC5kayJ9.Y1oJFYGgXuSbSuz-YGeT-ROqOF93puzZvBLvcNSLELY

###

GET http://localhost:7008/api/events

###

GET http://localhost:7008/api/events/status/ONGOING

###

POST http://localhost:7008/api/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcm91cCBvbmUiLCJzdWIiOiIxMjM0NTY3ODkxMEAxMjM0NTY3ODkxMC5kayIsImV4cCI6MTcxMjI1NjU3NCwicm9sZXMiOiJJTlNUUlVDVE9SIiwidXNlcm5hbWUiOiIxMjM0NTY3ODkxMEAxMjM0NTY3ODkxMC5kayJ9.Y1oJFYGgXuSbSuz-YGeT-ROqOF93puzZvBLvcNSLELY

{
  "title":"newTestEvent",
  "description":"This is a new test event!",
  "price":100.0,
  "createdAt":"2024-04-03",
  "updatedAt":"2024-04-03",
  "imageUrl":"www.moretexturl.com",
  "locations":[
    {
      "street":"test-street-wahoo",
      "eventSpec":{
        "date":"2024-05-05",
        "time":"16:30",
        "duration":2,
        "instructorName":"Peter Maker",
        "instructorEmail":"Peter@Maker.dk",
        "status":"UPCOMING",
        "category":"EVENT",
        "capacity":1200
      },
      "zipcodes":[
        {
          "zip":4700
        }
      ]
    },
    {
    "street":"the-other-test-street-wahoo",
    "eventSpec":{
      "date":"2024-06-08",
      "time":"17:30",
      "duration":3,
      "instructorName":"Morten Bungi",
      "instructorEmail":"Morten@Bungi.dk",
      "status":"UPCOMING",
      "category":"EVENT",
      "capacity":500
    },
      "zipcodes":[
        {
          "zip":3990
        }
      ]
    }
  ]
}

###

GET http://localhost:7008/api/admin/get_all_users
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcm91cCBvbmUiLCJzdWIiOiJwYXRyaWNrX3RoZV9hd2Vzb21lMl8xMjM0NTY3ODkxMEAxMjM0NTY3ODkxMC5kayIsImV4cCI6MTcxMjMwNDM2Niwicm9sZXMiOiJBRE1JTiIsInVzZXJuYW1lIjoicGF0cmlja190aGVfYXdlc29tZTJfMTIzNDU2Nzg5MTBAMTIzNDU2Nzg5MTAuZGsifQ.D2FUpfxov9G-jZZr5LwJx2biwBBUgZoJRYtktuRA4yI

### Instructor - Get All participants of Event

GET http://localhost:7008/api/events/?/users
Authorization: BEARER